export default {
  index: "6. Move 기초",
  module: "6.1 Module",
  comments: "6.2 주석",
  "primitive-types": "6.3 기본 타입",
  address: "6.4 주소 타입",
  expression: "6.5 표현식",
  struct: "6.6 Structs",
  "abilities-introduction": "6.7 Abilities: 소개",
  "drop-ability": "6.8 Ability: Drop",
  "importing-modules": "6.9 Module 가져오기",
  "standard-library": "6.10 표준 라이브러리",
  vector: "6.11 Vector",
  option: "6.12 Option",
  string: "6.13 String",
  "control-flow": "6.14 Control Flow",
  "enum-and-match": "6.15 Enums and Match",
  constants: "6.16 Constants",
  "assert-and-abort": "6.17 Aborting Execution",
  function: "6.18 Functions",
  "struct-methods": "6.19 Struct Methods",
  visibility: "6.20 Visibility Modifiers",
  "ownership-and-scope": "6.21 Ownership and Scope",
  "copy-ability": "6.22 Ability: Copy",
  references: "6.23 References",
  generics: "6.24 Generics",
  "type-reflection": "6.25 Type Reflection",
  testing: "6.26 Testing"
}