export default {
  index: "Move 기초",
  module: "Module",
  comments: "주석",
  "primitive-types": "기본 타입",
  address: "주소 타입",
  expression: "표현식",
  struct: "Structs",
  "abilities-introduction": "Abilities: 소개",
  "drop-ability": "Ability: Drop",
  "importing-modules": "Module 가져오기",
  "standard-library": "표준 라이브러리",
  vector: "Vector",
  option: "Option",
  string: "String",
  "control-flow": "Control Flow",
  "enum-and-match": "Enums and Match",
  constants: "Constants",
  "assert-and-abort": "Aborting Execution",
  function: "Functions",
  "struct-methods": "Struct Methods",
  visibility: "Visibility Modifiers",
  "ownership-and-scope": "Ownership and Scope",
  "copy-ability": "Ability: Copy",
  references: "References",
  generics: "Generics",
  "type-reflection": "Type Reflection",
  testing: "Testing"
}