export default {
  index: "Move Basics",
  module: "Modules",
  comments: "Comments",
  "primitive-types": "Primitive Types",
  address: "Address Type",
  expression: "Expressions",
  struct: "Structs",
  "abilities-introduction": "Abilities: Introduction",
  "drop-ability": "Ability: Drop",
  "importing-modules": "Importing Modules",
  "standard-library": "Standard Library",
  vector: "Vector",
  option: "Option",
  string: "String",
  "control-flow": "Control Flow",
  "enum-and-match": "Enums and Match",
  constants: "Constants",
  "assert-and-abort": "Aborting Execution",
  function: "Functions",
  "struct-methods": "Struct Methods",
  visibility: "Visibility Modifiers",
  "ownership-and-scope": "Ownership and Scope",
  "copy-ability": "Ability: Copy",
  references: "References",
  generics: "Generics",
  "type-reflection": "Type Reflection",
  testing: "Testing"
}