export default {
  index: "Advanced Programmability",
  "transaction-context": "Transaction Context",
  "module-initializer": "Module Initializer",
  capability: "Pattern: Capability",
  "epoch-and-time": "Epoch and Time",
  collections: "Collections",
  "wrapper-type-pattern": "Pattern: Wrapper Type",
  "dynamic-fields": "Dynamic Fields",
  "dynamic-object-fields": "Dynamic Object Fields",
  "dynamic-collections": "Dynamic Collections",
  "witness-pattern": "Pattern: Witness",
  "one-time-witness": "One Time Witness",
  publisher: "Publisher Authority",
  display: "Object Display",
  events: "Events",
  "balance-and-coin": "Balance & Coin",
  "sui-framework": "Sui Framework",
  "hot-potato-pattern": "Pattern: Hot Potato",
  bcs: "BCS",
  "fast-path": "Fast Path",
  "object-capability": "Pattern: Object Capability",
  "authorization-patterns": "Authorization Patterns",
  "cryptography-and-hashing": "Cryptography and Hashing",
  randomness: "Randomness"
}