export default {
  index: "9. 고급 프로그래밍 기법",
  "transaction-context": "9.1 트랜잭션 컨텍스트",
  "module-initializer": "9.2 Module 초기화",
  capability: "9.3 패턴: Capability",
  "epoch-and-time": "9.4 에포크와 시간",
  collections: "9.5 컬렉션",
  "wrapper-type-pattern": "9.6 패턴: Wrapper Type",
  "dynamic-fields": "9.7 동적 필드",
  "dynamic-object-fields": "9.8 동적 Object 필드",
  "dynamic-collections": "9.9 동적 컬렉션",
  "witness-pattern": "9.10 패턴: Witness",
  "one-time-witness": "9.11 One Time Witness",
  publisher: "9.12 Publisher 권한",
  display: "9.13 Object Display",
  events: "9.14 이벤트",
  "sui-framework": "9.15 Sui 프레임워크",
  "hot-potato-pattern": "9.16 패턴: Hot Potato",
  bcs: "9.17 BCS"
}