export default {
  index: "고급 프로그래밍 기법",
  "transaction-context": "트랜잭션 컨텍스트",
  "module-initializer": "Module 초기화",
  capability: "패턴: Capability",
  "epoch-and-time": "에포크와 시간",
  collections: "컬렉션",
  "wrapper-type-pattern": "패턴: Wrapper Type",
  "dynamic-fields": "동적 필드",
  "dynamic-object-fields": "동적 Object 필드",
  "dynamic-collections": "동적 컬렉션",
  "witness-pattern": "패턴: Witness",
  "one-time-witness": "One Time Witness",
  publisher: "Publisher 권한",
  display: "Object Display",
  events: "이벤트",
  "sui-framework": "Sui 프레임워크",
  "hot-potato-pattern": "패턴: Hot Potato",
  bcs: "BCS"
}