export default {
  index: "1. Move Reference",
  modules: "2. Modules",
  packages: "3. Packages",
  "primitive-types": "4. Primitive Types",
  variables: "5. Variables",
  constants: "6. Constants",
  generics: "7. Generics",
  equality: "8. Equality",
  "abort-and-assert": "9. Abort and Assert",
  "control-flow": "10. Control Flow",
  functions: "11. Functions",
  structs: "12. Structs",
  enums: "13. Enums",
  abilities: "14. Abilities",
  uses: "15. Uses",
  friends: "16. Friends",
  "method-syntax": "17. Method Syntax",
  "index-syntax": "18. Index Syntax",
  "unit-testing": "19. Unit Testing",
  "coding-conventions": "20. Coding Conventions"
}
